on:
  pull_request
  
jobs:
  CheckDeadLinks:
    runs-on: ubuntu-latest
    if: (github.repository == 'Beacontownfc/paddle_luke')
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          folder-path: '../'
