name: Scheduled Merge

on:
  issues:
    types: [opened]

jobs:
  # The purpose of this workflow is to periodically merge "asf-staging" into "asf-site"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      
      - name: scheduled crawl linkis website contributor
      - uses: ./.github/actions/Contributor_crawel
        with:
          repo: apache/incubator-linkis-website
          num: 1000
      
      - name: scheduled crawl linkis contributor
      - uses: ./.github/actions/Contributor_crawel
        with:
          repo: apache/incubator-linkis
          num: 1000
        
      - name: scheduled website contributor 
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /home/runner/work/incubator-linkis-website/incubator-linkis-website/
          publish_branch: main
