name: PR has a valid Issue?

on:
  pull_request:
    types: [ edited, synchronize, opened, reopened ]

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Issue number validator"
        uses: ./.github/actions/PR_has_a_valid_issue/
        id: validator
        with:
          prbody: ${{ github.event.pull_request.body }}
          prurl: ${{ github.event.pull_request.url }}
      
      - name: "print"
        run: |
          echo ${{ steps.validator.outputs.issueNumber }}

      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ steps.validator.outputs.issueNumber }}
          comment: Auto-closing issue
        env:
          Github_Token: ${{ secrets.GITHUB_TOKEN }}
          PRNUM: ${{ github.event.pull_request.number }}
