on:
  pull_request:
    # we use the `edited` type to detect changes to the PR title
    types: [opened, edited, synchronize, reopened]

jobs:
  linked_issues:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Find Linked Issues
        id: links
        uses: hossainemruz/linked-issues@main
        with:
          pr_url: ${{github.event.pull_request.html_url}}
          format: IssueNumber

      - name: Output linked Issue list
        run: echo "${{ steps.links.outputs.issues }}"
